import Head from "next/head";
import styles from "../styles/Home.module.css";
import LoginUser from "../components/LoginUser/LoginUser";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AsDeporte App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconAD.ico" />
      </Head>

      <main className={styles.main}>
        <LoginUser></LoginUser>
      </main>
      <Footer></Footer>
    </div>
  );
}
